### ISSUE TITLE
clone失败

### ISSUE THREAD

**Issue by maybug** [wistbean/learn_python3_spider#11] opened 2020-02-04 00:23 UTC
19052225@68A036519052225 MINGW64 /d/sipder
$ git clone https://github.com/wistbean/learn_python3_spider
Cloning into 'learn_python3_spider'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 4546 (delta 1), reused 0 (delta 0), pack-reused 4538
Receiving objects: 100% (4546/4546), 21.89 MiB | 5.62 MiB/s, done.
Resolving deltas: 100% (310/310), done.
error: invalid path '全国高考历年录取分数据/
2006-2017上海高考录取分数线（汇总）
.html'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by wistbean** [comment] 2020-05-09 11:43
Duplicate of #18

**Closed** 2020-05-09 11:44 UTC
